name = "gprbuild"
version = "23.0.0"
description = "The GPRBuild Ada/multilanguage build tool"
maintainers = ["chouteau@adacore.com", "jeremy@synack.me"]
maintainers-logins = ["Fabien-Chouteau", "JeremyGrosser"]

auto-gpr-with = false

[environment]
PATH.prepend = "${CRATE_ROOT}/bin"

[configuration]
disabled = true

[origin."case(os)".linux."case(host-arch)".x86-64]
url = "https://pub.synack.me/artifacts/gprbuild-23.0.0-x86_64-linux.tar.bz2"
hashes = ["sha256:0d16c4c76a2f024b6a2ca6caa7ef215532a8afa54a74e720ddfc014c614a2e21"]
